#!/bin/bash

PROGRAM_NAME=$(basename $0)

function usage() {
    echo "Usage: $PROGRAM_NAME INPUT OUTPUT"
    exit $1
}

if [[ "$#" -eq "1" ]] && [[ "$1" == "--help" ]] ; then
    usage 0
fi

if [[ "$#" -eq 2 ]] ; then
    INPUT=$1
    OUTPUT=$2
    mkdir -p $OUTPUT
    gpgtar --decrypt -C $OUTPUT $INPUT
    exit $?
fi

usage 1
